### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ghost** [gpenverne/putio-mount#10]
doomicle@doomicle-VirtualBox:~/Downloads/putio-mount-master$ sudo python ./putiomount.py /mnt/putio
Traceback (most recent call last):
  File "./putiomount.py", line 4, in <module>
    PutioMount.mount(sys.argv[1])
  File "/home/doomicle/Downloads/putio-mount-master/PutioMount/__init__.py", line 360, in mount
    config = json.loads(f.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ghost** [comment]
Nevermind. The issue was I had to copy the .putio-config sample file from the setup directory. (I just created one of my own without realising there was a file with necessary data in it that needed to be edited).
